In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [2]:
tsize=0.30
df_2= pd.read_csv('data_preprocessed.csv')
df_2

,ttime,pm1,pm2,pm3,sm,lum,temp,humd,pres
0,18-07-2022 15:39,0.83,0.00,0.00,7463,8379.8,23.02,90.57,92849.25
1,18-07-2022 15:44,1.39,0.00,0.00,7576,8379.8,23.47,88.37,92848.31
2,18-07-2022 15:49,1.95,0.00,0.00,7576,8379.8,23.64,85.26,92844.82
3,18-07-2022 15:54,2.51,0.00,0.00,7463,8379.8,23.62,85.93,92834.94
4,18-07-2022 15:59,0.55,2.51,2.51,7463,8379.8,23.82,86.06,92815.25
...,...,...,...,...,...,...,...,...,...
20161,10-03-2023 08:59,0.55,1.11,27.38,327,5366.0,27.04,32.24,93560.72
20162,10-03-2023 09:27,1.11,1.11,27.38,327,7359.0,28.53,28.69,93574.12
20163,10-03-2023 09:55,1.67,1.11,27.38,327,7359.0,30.07,24.39,93571.75
20164,10-03-2023 10:23,0.55,1.67,27.93,327,8386.0,31.55,22.99,93558.36
20165,10-03-2023 10:51,1.11,1.67,27.93,328,8954.0,32.68,20.85,93541.99

In [3]:
X= df_2[['pm1', 'pm2', 'pm3','lum', 'temp', 'humd','pres']]
y=df_2['sm']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = tsize, random_state = 0)
rfr = RandomForestRegressor(n_estimators=100)
rfr.fit(X_train, y_train)

In [ ]:
df = pd.read_csv('file_name.csv') #filename of March-data from user2 in CSV format

March_features = df[['pm3','am','st', 'lum']]#taking the features
rfr_pred = rfr.predict(March_features)#generating predictions

pred_df = pd.DataFrame({'ttime':df['ttime'], 'pred_sm':rfr_pred})
pred_df.to_csv('user2_March_predictions.csv')